### ISSUE TITLE
lib Folder to sp1 Template

### ISSUE THREAD

**Issue by 0xVikasRushi** [succinctlabs/sp1-project-template#21]
I’ve been working with the sp1 template and noticed that managing shared code between program, and script is challenging. I’ve had to copy and paste code frequently, which is inefficient. it would be helpful if you add a `lib` for common rust code.

currently my folder structure looks something like these
```
bitcoin-spv/
├── lib/
│   ├── Cargo.toml
│   └── src/
│       └── lib.rs
├── program/
│   ├── Cargo.toml
│   └── src/
│       └── main.rs
├── script/
│   ├── Cargo.toml
│   └── src/
│       ├── bin/
│           ├── prove.rs
│           └── vkey.rs
└── rust-toolchain

```

**Comment by ctian1** [comment]
Added in #24!
